########################################
### Building a multi-stage image with Google Distroless base image
#############################################
# STAGE 1: Builder
FROM golang:1.21-alpine as builder

WORKDIR /app

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o timer .

# STAGE 2: Runtime with Google Distroless
FROM gcr.io/distroless/base-debian11

WORKDIR /app

# Copy the compiled binary from the builder stage
COPY --from=builder /app/timer /app

ENTRYPOINT [ "/app" ]
